# -*- coding: utf-8 -*-
"""declaration of variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j98PAIoanJOOVOJb3rUmvUNw90zrc3SW
"""

#declaring variables and printing
a=29
b=2.6
d="Hello"
print(a)
print(b)
print(d)