# -*- coding: utf-8 -*-
"""print function.Py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ain3IpHZYYdB0A2WvuoAofNO2ftfeorW
"""

#PRINTING OF A TEXT IN PYTHON
print("Hello World!!")