# -*- coding: utf-8 -*-
"""type of variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10a4PLIL3cwJIJZoY5VwKcmrfsRPKHCTs
"""

#printing the type of the variable
a=2
b=2.8
c='a'
print(type(a))
print(type(b))
print(type(c))